Parameters:
  SSHAccessAddresses:
    Type: String
    Default: 0.0.0.0/0
    Description: Addreses that will have SSH access to the instance
    AllowedPattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}$
  KeyNameParameter:
    Type: String
    Default: US-West-2-key
    Description: Key to SSH into the instance
  AssetsBucketName:
    Type: String
    Description: Name of bucket to download assets from

Resources:
  MLFlowBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain

  MLFlowInstanceSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow public HTTP access and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref SSHAccessAddresses
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MLFlowSG
        - Key: Description
          Value: SG for MLFlow Instance
  MLFlowInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: !Ref KeyNameParameter
      InstanceType: t3.small
      ImageId: "ami-0ca5c3bd5a268e7db"
      IamInstanceProfile: !Ref MLFLowInstanceProfile
      SecurityGroups:
        - !Ref MLFlowInstanceSG
      Tags:
        - Key: Name
          Value: MLFlowInstance
        - Key: Description
          Value: Instance for running an MLFlow Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update && apt upgrade -y && apt install -y python3 python3-pip nginx
          pip3 install -U pip
          pip3 install botocore==1.18.14 awscli==1.18.155 boto3==1.15.14 mlflow
          aws s3 cp s3://${AssetsBucketName}/assets/${AWS::StackName}/mlflow-bootstrap.sh /tmp/mlflow-bootstrap.sh
          export ASSETS_BUCKET=${AssetsBucketName}
          export MLFLOW_BUCKET=${MLFlowBucket}
          source /tmp/mlflow-bootstrap.sh && rm /tmp/mlflow-bootstrap.sh
  MLFLowInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: MLFlowInstanceProfile
      Roles:
        - !Ref MLFlowInstanceRole
  MLFlowInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "mlflow-instance-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: StorageBucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:DeleteObject"
                  - "s3:DeleteObjectVersion"
                  - "s3:RestoreObject"
                  - "s3:AbortMultipartUpload"
                Resource:
                  - !GetAtt MLFlowBucket.Arn
                  - !Sub "${MLFlowBucket.Arn}/*"
        - PolicyName: AssetsBucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                Resource:
                  - !Sub "arn:aws:s3:::${AssetsBucketName}"
                  - !Sub "arn:aws:s3:::${AssetsBucketName}/*"

Outputs:
  InstanceIP:
    Description: Public IP of the instance.
    Value: !GetAtt MLFlowInstance.PublicIp

  InstanceDNS:
    Description: Public DNS name of the instance
    Value: !GetAtt MLFlowInstance.PublicDnsName
