Parameters:
  SSHAccessAddresses:
    Type: String
    Default: 0.0.0.0/0
    Description: Addreses that will have SSH access to the instance
    AllowedPattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}$
  KeyNameParameter:
    Type: String
    Default: US-West-2-key
    Description: Key to SSH into the instance
  AssetsBucketName:
    Type: String
    Description: Name of bucket to download assets from

Resources:
  MLFlowInstanceSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow public HTTP access and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref SSHAccessAddresses
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MLFlowSG
        - Key: Description
          Value: SG for MLFlow Instance
  MLFlowInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: !Ref KeyNameParameter
      InstanceType: t3.small
      ImageId: "ami-0ca5c3bd5a268e7db"
      IamInstanceProfile: !Ref MLFLowInstanceProfile
      SecurityGroups:
        - !Ref MLFlowInstanceSG
      Tags:
        - Key: Name
          Value: MLFlowInstance
        - Key: Description
          Value: Instance for running an MLFlow Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update && apt install -y python3 python3-pip awscli
          aws s3 cp s3://${AssetsBucketName}/assets/${AWS::StackName}/mlflow-bootstrap.sh /tmp/mlflow-bootstrap.sh
          source /tmp/mlflow-bootstrap.sh
          rm /tmp/mlflow-bootstrap.sh
  MLFLowInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: MLFlowInstanceProfile
      Roles:
        - !Ref MLFlowInstanceRole
  MLFlowInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "mlflow-instance-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: AssetsBucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                Resource:
                  - !Sub "arn:aws:s3:::${AssetsBucketName}"
                  - !Sub "arn:aws:s3:::${AssetsBucketName}/*"
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mlflow/*"
  BucketNameSSM:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /mlflow/assets-bucket-name-ssm
      Tier: Standard
      Type: String
      Value: !Ref AssetsBucketName
      Description: Name of the assets bucket to be accessed from the instance