Parameters:
  AccessAddressesParameter:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR range of adresses to have ssh access to the instance
    AllowedPattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}$

  KeyNameParameter:
    Type: String
    Default: US-West-2-key
    Description: Name of key to use to ssh into the instance

Resources:
  StorageBucket:
    Type: "AWS::S3::Bucket"

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: !Ref KeyNameParameter
      InstanceType: t2.micro
      IamInstanceProfile: !Ref InstanceProfile
      # Amazon Linux 2
      ImageId: "ami-0e999cbd62129e3b1"
      SecurityGroups:
        - !Ref InstanceSG

  InstanceSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable access on port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref AccessAddressesParameter
        - IpProtocol: tcp
          FromPort: "9000"
          ToPort: "9000"
          CidrIp: !Ref AccessAddressesParameter

  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: "training-instance-role"
      Policies:
        - PolicyName: BucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetAccessPoint"
                  - "s3:ListAllMyBuckets"
                  - "s3:ListAccessPoints"
                  - "s3:CreateJob"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetObjectVersion"
                  - "s3:DeleteObject"
                  - "s3:DeleteObjectVersion"
                  - "s3:RestoreObject"
                  - "s3:AbortMultipartUpload"
                Resource: "arn:aws:s3:::training-instance-*"

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: training-instance-profile
      Roles:
        - !Ref InstanceRole
