Resources:

  ############################################################################
  # VPC and Gateway
  ############################################################################
  StackVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "false"
      Tags:
        - Key: Name
          Value: StackVPC
        - Key: Description
          Value: "VPC created by CloudFormation stack"
  StackIG:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: StackIG
  VPCGatewayAssoc:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref StackVPC
      InternetGatewayId: !Ref StackIG

  ############################################################################
  # Subnets
  ############################################################################

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref StackVPC
      Tags:
        - Key: Name
          Value: PublicSubnet1
        - Key: Description
          Value: "A public subnet of the VPC"

  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref StackVPC
      Tags:
        - Key: Name
          Value: PrivateSubnet1
        - Key: Description
          Value: "A private subnet of the VPC"

  ############################################################################
  # Public ACL
  ############################################################################

  PublicACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: !Ref StackVpc
      Tags:
        - Key: Name
          Value: PublicACL
        - Key: Description
          Value: "ACL for public subnet."

  PublicACLAssoc:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet
      NetworkAclId: !Ref PublicACL

  PublicInboundRule:
    Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId: !Ref PublicACL
        RuleNumber: 100
        Protocol: -1
        RuleAction: allow
        Egress: false
        CidrBlock: 0.0.0.0/0

  PublicToPrivateRule:
    Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId: !Ref PublicACL
        RuleNumber: 100
        Protocol: -1
        RuleAction: allow
        Egress: true
        CidrBlock: 10.0.2.0/24

  PublicOutboundRule:
    Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId: !Ref PublicACL
        RuleNumber: 200
        Protocol: -1
        RuleAction: allow
        Egress: true
        CidrBlock: 0.0.0.0/0

  ############################################################################
  # Private ACL
  ############################################################################

  PrivateACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: !Ref StackVpc
      Tags:
        - Key: Name
          Value: PrivateACL
        - Key: Description
          Value: "ACL for private subnet."

  PrivateACLAssoc:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet
      NetworkAclId: !Ref PrivateACL

  PrivateInboundRule:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 10.0.1.0/24

  PrivateOutboundRule:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
